import React from 'react';

/**
 * DailyFeed Component
 * 
 * This serves as the "Third Tab" (next to Gmail and Google Chat) on the 
 * Small Business Owner's HUB Overlay. It abstracts away the complex Graph 
 * and Vector Database into a simple, conversational summary generated by Paperclip AI.
 */
export default function DailyFeed() {
  return (
    <div className="flex flex-col h-full bg-white dark:bg-zinc-900 border-l border-zinc-200 dark:border-zinc-800 p-6 overflow-y-auto">
      <div className="mb-8">
        <h2 className="text-2xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-100">
          Paperclip Daily Digest
        </h2>
        <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
          Semantic summaries built from your connected Google Workspace and Hub Graph.
        </p>
      </div>

      {/* Mocked Feed Entries based on the Graph & Vectors */}
      <div className="space-y-6">
        
        <div className="p-4 rounded-xl bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-800/50">
          <div className="flex items-center gap-2 mb-2 text-sm font-medium text-blue-900 dark:text-blue-300">
            <span className="w-2 h-2 rounded-full bg-blue-500"></span>
            Drive & KPI Insight
          </div>
          <p className="text-zinc-700 dark:text-zinc-300 text-sm leading-relaxed">
            I noticed you updated the <strong>Q3 Projections Sheet</strong> in Drive. 
            Based on those new numbers, I&apos;ve linked the data to your <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-zinc-200 dark:bg-zinc-700 text-zinc-800 dark:text-zinc-200 cursor-pointer hover:bg-zinc-300 transition-colors">[[kpi:Revenue|Q3 Revenue]]</span> KPI. 
            It looks like we are trending 12% higher than expected.
          </p>
        </div>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-800/50 border border-zinc-100 dark:border-zinc-800">
          <div className="flex items-center gap-2 mb-2 text-sm font-medium text-zinc-900 dark:text-zinc-300">
            <span className="w-2 h-2 rounded-full bg-amber-500"></span>
            Gmail Action Item
          </div>
          <p className="text-zinc-700 dark:text-zinc-300 text-sm leading-relaxed">
            A client emailed you about a delayed shipment. I&apos;ve automatically created a <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-zinc-200 dark:bg-zinc-700 text-zinc-800 dark:text-zinc-200 cursor-pointer hover:bg-zinc-300 transition-colors">[[task:102|Logistics Issue]]</span> node in the Graph and pinged the fulfillment agent.
          </p>
        </div>

      </div>
    </div>
  );
}
